# Generated by Django 4.2 on 2023-04-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=255)),
                ('Payment_Type', models.CharField(choices=[('in', 'доход'), ('out', 'расход')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_FName', models.CharField(default='-', max_length=255)),
                ('User_MName', models.CharField(default='-', max_length=255)),
                ('User_LName', models.CharField(default='-', max_length=255)),
                ('User_Login', models.CharField(max_length=255, unique=True)),
                ('User_Password', models.CharField(max_length=255)),
                ('Wallet', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Time', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.FloatField()),
                ('Method', models.CharField(choices=[('RUB', 'руб'), ('EUR', 'евро'), ('USD', 'доллар')], max_length=255)),
                ('Comment', models.TextField(default='-')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageCash.category')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageCash.user')),
            ],
        ),
    ]
